export let projects = [
  {
    id: 1,
    image: 'assets/img/projects/mone_mobile.png',
    title: 'Mercury|One',
    category: 'Mobile',
    client: 'aboveo',
    date: null,
    description: 'Html, Css/Sass, Bootstrap, Javascript / jQuery / Typescript',
    link: 'https://apps.apple.com/us/app/mercury-one/id1015811834',
  },
  {
    id: 2,
    image: 'assets/img/projects/trunow_mobile.png',
    title: 'Trunow',
    category: 'Mobile',
    client: 'Trunow',
    date: null,
    description: 'Ionic Framework, Angular',
    link:
      'https://apps.apple.com/us/app/trunow-earn-rewards-on-purchases/id1256870067',
  },
  {
    id: 3,
    image: 'assets/img/projects/trunow_re_mobile.png',
    title: 'Trunow Retailer',
    category: 'Mobile',
    client: 'Trunow',
    date: null,
    description: 'Ionic Framework, Angular',
    link: 'https://apps.apple.com/us/app/retailernow/id1404731043',
  },
  {
    id: 4,
    image: 'assets/img/projects/trunow_lo_mobile.png',
    title: 'Trunow Locations',
    category: 'Mobile',
    client: 'Trunow',
    date: null,
    description: 'Ionic Framework, Angular',
    link: 'https://apps.apple.com/us/app/locationsnow/id1257581248',
  },
  {
    id: 5,
    image: 'assets/img/projects/mone_inv_mobile.png',
    title: 'Mercury|One Inventory',
    category: 'Mobile',
    client: 'aboveo',
    date: null,
    description: 'Ionic Framework, Angular',
    link:
      'https://play.google.com/store/apps/details?id=com.aboveo.mercuryoneinv&hl=en_US',
  },
  // {
  //   id: 6,
  //   image: 'assets/img/projects/flip_mobile_driver.png',
  //   title: 'Flip.Casa Driver',
  //   category: 'Mobile',
  //   client: 'Flip.Casa',
  //   date: null,
  //   description: 'Ionic Framework, Angular, Node Js, PostgreSql',
  //   link: 'https://play.google.com/store/apps/details?id=com.flipcasa.driver'
  // },
  {
    id: 7,
    image: 'assets/img/projects/sold_website.png',
    title: 'SoldnPay',
    category: 'Website',
    client: 'aboveo',
    date: null,
    description: 'Angular 8',
    link: 'http://soldnpay.aboveo.com',
  },
  {
    id: 8,
    image: 'assets/img/projects/trunow_website.png',
    title: 'Trunow',
    category: 'Website',
    client: 'Trunow',
    date: null,
    description: 'Javascript',
    link: 'https://trunow.com',
  },
  {
    id: 9,
    image: 'assets/img/projects/trunow_re_website.png',
    title: 'Trunow Retailer',
    category: 'Website',
    client: 'Trunow',
    date: null,
    description: 'Angular 8',
    link: 'https://retailer.trunow.com/',
  },
  {
    id: 10,
    image: 'assets/img/projects/endo_website.png',
    title: 'EndoHealthAtlanta',
    category: 'Website',
    client: 'aboveo',
    date: null,
    description: 'ASP .Net',
    link: 'http://www.endohealthatlanta.com/',
  },
  {
    id: 11,
    image: 'assets/img/projects/inc_website.png',
    title: 'IncuStart',
    category: 'Website',
    client: 'aboveo',
    date: null,
    description: 'ASP .Net',
    link: 'http://incustart.com/',
  },
  {
    id: 12,
    image: 'assets/img/projects/asa_wesite.png',
    title: 'ASA',
    category: 'Website',
    client: 'aboveo',
    date: null,
    description: 'Angular 8',
    link: 'http://asa.help/',
  },
  {
    id: 13,
    image: 'assets/img/projects/mone_setup.png',
    title: 'Mercuryone Setup',
    category: 'Mobile',
    client: 'ABOVEO',
    date: null,
    description: 'Flutter',
    link: 'https://monefinancial.aboveo.com/',
  },
  {
    id: 14,
    image: 'assets/img/projects/sri_website.png',
    title: 'Sree Lakshmi Agencies',
    category: 'Website',
    client: 'Sree Lakshmi Agencies',
    date: null,
    description: 'ASP .Net',
    link: null,
  },
  {
    id: 15,
    image: 'assets/img/projects/pre_website.png',
    title: 'Premier Cosmetic Surg',
    category: 'Website',
    client: 'Premier Cosmetic Surg',
    date: null,
    description: 'ASP .Net',
    link: null,
  },
  {
    id: 16,
    image: 'assets/img/projects/solar_website.png',
    title: 'Inodaya Solar',
    category: 'Website',
    client: 'Inodaya Solar',
    date: null,
    description: 'ASP .Net',
    link: null,
  },
  {
    id: 17,
    image: 'assets/img/projects/abroad_website.png',
    title: 'AbroadOne',
    category: 'Website',
    client: 'AbroadOne',
    date: null,
    description: 'Javascript',
    link: null,
  },
  {
    id: 18,
    image: 'assets/img/projects/sold_portal.png',
    title: 'SoldnPay',
    category: 'Portal',
    client: 'aboveo',
    date: null,
    description: 'Angular 8',
    link: 'http://scandata.aboveo.com',
  },
  {
    id: 19,
    image: 'assets/img/projects/tunow_re_portal.png',
    title: 'Trunow Retailer',
    category: 'Portal',
    client: 'Trunow',
    date: null,
    description: 'Angular 8',
    link: 'https://secureretailer.trunow.com/',
  },
  {
    id: 20,
    image: 'assets/img/projects/saasoa_portal.png',
    title: 'SAASOA',
    category: 'Portal',
    client: 'aboveo',
    date: null,
    description: 'Angular 8',
    link: 'https://adminsaasoa.aboveo.com/',
  },
  {
    id: 21,
    image: 'assets/img/projects/trunow_admin_portal.png',
    title: 'Trunow',
    category: 'Portal',
    client: 'Trunow',
    date: null,
    description: 'Angular 8',
    link: null,
  },
  {
    id: 22,
    image: 'assets/img/projects/trunow_scanbook_portal.png',
    title: 'Scan Book',
    category: 'Portal',
    client: 'aboveo',
    date: null,
    description: 'Angular 8',
    link: null,
  },
  {
    id: 23,
    image: 'assets/img/projects/market_portal.png',
    title: 'Market Data',
    category: 'Portal',
    client: 'aboveo',
    date: null,
    description: 'Angular 8',
    link: 'http://marketdatagrocery.aboveo.com',
  },
  {
    id: 24,
    image: 'assets/img/projects/crm_portal.png',
    title: 'Aboveo CRM',
    category: 'Portal',
    client: 'aboveo',
    date: null,
    description: 'Angular 8',
    link: 'http://crm.aboveo.com/',
  },
  {
    id: 25,
    image: 'assets/img/projects/asa_portal.png',
    title: 'ASA',
    category: 'Portal',
    client: 'aboveo',
    date: null,
    description: 'Angular 8, Node js, Mongodb',
    link: 'http://id1admin.asa.help',
  },
  {
    id: 26,
    image: 'assets/img/projects/undisclosed_portal.png',
    title: 'Admin',
    category: 'Portal',
    client: 'undisclosed',
    date: null,
    description: 'Angular 9, Node js',
    link: 'null',
  },
  {
    id: 27,
    image: 'assets/img/projects/spin_portal.png',
    title: 'SPIAN',
    category: 'Portal',
    client: 'SRKIT',
    date: null,
    description: 'ASP .Net',
    link: 'https://spian.azurewebsites.net/',
  },
  {
    id: 28,
    image: 'assets/img/projects/mone_finanical.png',
    title: 'FINANCIAL',
    category: 'Portal',
    client: 'ABOVEO',
    date: null,
    description: 'Angular 8, NestJS, Postgres',
    link: 'https://monefinancial.aboveo.com/',
  },
  {
    id: 29,
    image: 'assets/img/projects/altranz.png',
    title: 'Altranz',
    category: 'Portal',
    client: 'altranz',
    date: null,
    description: 'Angular 9, Node js, Postgres',
    link: '',
  },
  {
    id: 30,
    image: 'assets/img/projects/kiosk.png',
    title: 'Kiosk',
    category: 'Website',
    client: 'ceras',
    date: null,
    description: 'Javascript, Css, Html',
    link: '',
  },
  {
    id: 31,
    image: 'assets/img/projects/ceras.png',
    title: 'Ceras',
    category: 'Website',
    client: 'ceras',
    date: null,
    description: 'Angular, Css, Html, Tailwind',
    link: '',
  },
  // {
  //   id: 30,
  //   image: 'assets/img/projects/asa_admin.png',
  //   title: 'asa admin',
  //   category: 'Portal',
  //   client: 'asa',
  //   date: null,
  //   description: 'Angular 8, Node js, mongo',
  //   link: 'http://id1admin.asa.help/'
  // }
];
